//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagr {
	
	
	public partial class submitpost {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox spTitleBox;
		
		protected System.Web.UI.WebControls.TextBox spURLBox;
		
		protected System.Web.UI.WebControls.TextBox spDescriptionBox;
	}
}
