//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagr {
	
	
	public partial class tabs {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Button GIFSTabButton;
		
		protected System.Web.UI.WebControls.Button VideosTabButton;
		
		protected System.Web.UI.WebControls.Button ImagesTabButton;
		
		protected System.Web.UI.WebControls.Button LinksTabButton;
		
		protected System.Web.UI.WebControls.Button TextTabButton;
		
		protected System.Web.UI.WebControls.Button WorkTabButton;
	}
}
